config/routes.rb
Rails.application.routes.draw do
  resources :purchases
  devise_for :users

  devise_scope :user do
    get "/sign_in", :to => "devise/sessions#new"
  end

  resources :purchases do
    post 'add', to: 'purchases#addPurchase', on: :member
    get 'check', to: 'purchases#getPurchase', on: :member
    delete 'remove', to: 'purchases#removePurchase', on: :member
  end
  resources :games
  resources :users

  root to: 'games#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  before_action :set_purchase, only: [:show, :edit, :update, :destroy]

  # GET /purchases
  # GET /purchases.json
  def index
    @purchases = Purchase.all
  end

  # GET /purchases/1
  # GET /purchases/1.json
  def show
  end

  # GET /purchases/new
  def new
    @purchase = Purchase.new
  end

  # GET /purchases/1/edit
  def edit
  end

  def addPurchase
    game_id = params[:id]
    @purchase = Purchase.new
    @purchase.game_id = game_id
    @purchase.user_id = current_user.id
    puts @purchase
    @purchase.save
    jsonObj = { "ipurchasedIt" => checkPurchase(game_id) }
    respond_to do |format|
      format.json { render json: jsonObj }
    end
  end

  def checkPurchase(game_id)
    return current_user.purchases.where('game_id = ?', "#{game_id}").length > 0
  end

  def getPurchase()
    game_id = params[:id]
    @purchase = current_user.purchases.where('game_id = ?', "#{game_id}").first
    jsonObj = { "ipurchasedIt" => checkPurchase(game_id) }
    respond_to do |format|
      format.json { render json: jsonObj }
    end
  end

  def removePurchase
    game_id = params[:id]
    @purchase = current_user.purchases.where('game_id = ?', "#{game_id}").first
    Purchase.destroy(@purchase.id)
    puts checkPurchase(game_id)
    jsonObj = {"ipurchasedIt" => checkPurchase(game_id)}
    respond_to do |format|
      format.json { render json: jsonObj }
    end
  end

  # POST /purchases
  # POST /purchases.json
  def create
    @purchase = Purchase.new(purchase_params)

    respond_to do |format|
      if @purchase.save
        format.html { redirect_to @purchase, notice: 'Purchase was successfully created.' }
        format.json { render :show, status: :created, location: @purchase }
      else
        format.html { render :new }
        format.json { render json: @purchase.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /purchases/1
  # PATCH/PUT /purchases/1.json
  def update
    respond_to do |format|
      if @purchase.update(purchase_params)
        format.html { redirect_to @purchase, notice: 'Purchase was successfully updated.' }
        format.json { render :show, status: :ok, location: @purchase }
      else
        format.html { render :edit }
        format.json { render json: @purchase.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /purchases/1
  # DELETE /purchases/1.json
  def destroy
    @purchase.destroy
    respond_to do |format|
      format.html { redirect_to purchases_url, notice: 'Purchase was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_purchase
      @purchase = Purchase.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def purchase_params
      params.require(:purchase).permit(:user_id, :game_id)
    end
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/views/purchases/_form.html.erb
<%= form_for(purchase) do |f| %>
  <% if purchase.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(purchase.errors.count, "error") %> prohibited this purchase from being saved:</h2>

      <ul>
      <% purchase.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id %>
  </div>

  <div class="field">
    <%= f.label :game_id %>
    <%= f.text_field :game_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/purchases/edit.html.erb
<h1>Editing Purchase</h1>

<%= render 'form', purchase: @purchase %>

<%= link_to 'Show', @purchase %> |
<%= link_to 'Back', purchases_path %>

app/views/purchases/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Purchases</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Game</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @purchases.each do |purchase| %>
      <tr>
        <td><%= purchase.user %></td>
        <td><%= purchase.game %></td>
        <td><%= link_to 'Show', purchase %></td>
        <td><%= link_to 'Edit', edit_purchase_path(purchase) %></td>
        <td><%= link_to 'Destroy', purchase, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Purchase', new_purchase_path %>

app/views/purchases/new.html.erb
<h1>New Purchase</h1>

<%= render 'form', purchase: @purchase %>

<%= link_to 'Back', purchases_path %>

app/views/purchases/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @purchase.user %>
</p>

<p>
  <strong>Game:</strong>
  <%= @purchase.game %>
</p>

<%= link_to 'Edit', edit_purchase_path(@purchase) %> |
<%= link_to 'Back', purchases_path %>